[package]
name = "diya"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.32.1", features = ["bundled"] }
serenity = "0.12.2"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
